---
title: "TEs across histones"
author: "Renee Matthews"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```

```{r package loading}
library(tidyverse)
library(GenomicRanges)
library(plyranges)
library(genomation)
library(readr)
library(rtracklayer)
library(stringr)
library(ggrepel)
library(DT)
library(ChIPseeker)
library(ggVennDiagram)
library(smplot2)
```

First steps: Pulling and overlapping each ROI set with specific families of TEs 
```{r repeatmasker loading}

repeatmasker <- read_delim("data/Other_paper_data/repeatmasker_20250911.txt", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)


autosomes <- paste0("chr", 1:22)
repeatmasker_clean <- repeatmasker %>% mutate(
    strand = ifelse(strand == "C", "-", "+")
  ) %>% 
   mutate(
    start = genoStart + 1,
    end   = genoEnd)%>% 
  mutate(repFamily= str_remove(repFamily, "\\?$")) %>% 
  dplyr::filter(genoName %in% autosomes) %>% 
  mutate(RM_id=paste0(genoName,":",start,"-",end,":",id))


rpt_split <- split(repeatmasker_clean, repeatmasker_clean$repClass)

rpt_split_gr_list <- lapply(rpt_split, function(df) {
  GRanges(
    seqnames = df$genoName,
    ranges   = IRanges(start = df$start, end = df$end),
    strand   = df$strand,
    repName   = df$repName,
    repClass  = df$repClass,
    repFamily = df$repFamily,
    swScore   = df$swScore,
    milliDiv  = df$milliDiv,
    milliDel  = df$milliDel,
    milliIns  = df$milliIns,
    RM_id        = df$RM_id
  )
})



```

```{r subset rpt_split_gr_list}
SINE_gr <- rpt_split_gr_list$SINE
SINE_df <- SINE_gr %>% 
  as.data.frame()

SINE_split_df <- split(SINE_df, SINE_df$repFamily)

LINE_gr <- rpt_split_gr_list$LINE
LINE_df <- LINE_gr %>% 
  as.data.frame()

LINE_split_df <- split(LINE_df, LINE_df$repFamily)

LTR_gr <- rpt_split_gr_list$LTR
LTR_df <- LTR_gr %>% 
  as.data.frame()

LTR_split_df <- split(LTR_df, LTR_df$repFamily)

SVA_gr <- rpt_split_gr_list$Retroposon
SVA_df <- SVA_gr %>% 
  as.data.frame()

SVA_split_df <- split(SVA_df, SVA_df$repFamily)

DNA_gr <- rpt_split_gr_list$DNA
DNA_df <- DNA_gr %>% 
  as.data.frame()

DNA_split_df <- split(DNA_df, DNA_df$repFamily)


```

Pulling in ROI granges for H3K27ac and H3K9me3
```{r loading H3K9me3 data}

peakAnnoList_H3K9me3 <- readRDS("data/motif_lists/H3K9me3_annotated_peaks.RDS")
peakAnnoList_H3K27ac <- readRDS("data/motif_lists/H3K27ac_annotated_peaks.RDS")

H3K9me3_lookup <- imap_dfr(peakAnnoList_H3K9me3[1:3], ~
  tibble(Peakid = .x@anno$Peakid, cluster = .y)
)
H3K27ac_lookup <- imap_dfr(peakAnnoList_H3K27ac[1:3], ~
  tibble(Peakid = .x@anno$Peakid, cluster = .y)
)

H3K9me3_sets_gr <- lapply(peakAnnoList_H3K9me3, function(df) {
  as_granges(df)
})

H3K27ac_sets_gr <- lapply(peakAnnoList_H3K27ac, function(df) {
  as_granges(df)
})

annotated_H3K27ac_ext200 <- readRDS("data/TE_annotation/annotated_H3K27ac_ext200_TE_overlaps.RDS")

annotated_H3K9me3_ext200 <- readRDS("data/TE_annotation/annotated_H3K9me3_ext200_TE_overlaps.RDS")
all_H3K27ac_peaks <- annotated_H3K27ac_ext200 %>%
  dplyr::select(Peakid, cluster) %>%
  dplyr::distinct()
all_H3K9me3_peaks <- annotated_H3K9me3_ext200 %>%
  dplyr::select(Peakid, cluster) %>%
  dplyr::distinct()
```

```{r toplist data}
H3K9me3_toplist <- readRDS( "data/DER_data/H3K9me3_toplist_nooutlier.RDS")

H3K27ac_toplist <- readRDS( "data/DER_data/H3K27ac_toplist.RDS")

H3K27ac_toptable_list <- bind_rows(H3K27ac_toplist, .id = "group")

H3K9me3_toptable_list <- bind_rows(H3K9me3_toplist, .id = "group")

K9me3_lfctable <- H3K9me3_toptable_list %>% 
  dplyr::select(group,genes, logFC) %>% 
  pivot_wider(.,id_cols = genes, names_from = group, values_from = logFC)

K27ac_lfctable <- H3K27ac_toptable_list %>% 
  dplyr::select(group,genes, logFC) %>% 
  pivot_wider(.,id_cols = genes, names_from = group, values_from = logFC)

cluster_colors <- c("Set_1" = "#d93e40","Set_2" = "#1c9f50","Set_3" = "#3570b3","NA"  ="grey70")

```



getting counts of TE repFamilies between each data set:

```{r getting Rep families}
H3K27ac_family_count <- annotated_H3K27ac_ext200 %>% 
  dplyr::select(Peakid, repFamily,cluster) %>% 
  na.omit(repFamily) %>% 
  separate_longer_delim(repFamily,delim = ";") %>% 
 dplyr::distinct(Peakid, repFamily) %>%   # 🔑 KEY STEP
  dplyr::count(repFamily, name = "n_H3K27ac")


H3K9me3_family_count <- annotated_H3K9me3_ext200 %>% 
  dplyr::select(Peakid, repFamily,cluster) %>% 
  na.omit(repFamily) %>% 
  separate_longer_delim(repFamily,delim = ";") %>% 
 dplyr::distinct(Peakid, repFamily) %>%   # 🔑 KEY STEP
  dplyr::count(repFamily, name = "n_H3K9me3")



length(intersect(H3K27ac_family_count$repFamily,H3K9me3_family_count$repFamily))
all_families <- union(H3K27ac_family_count$repFamily,H3K9me3_family_count$repFamily)
```


```{r}
family_counts <- full_join(
  H3K27ac_family_count,
  H3K9me3_family_count,
  by = "repFamily"
) %>%
  tidyr::replace_na(list(n_H3K27ac = 0, n_H3K9me3 = 0))

### adding in totals and totals without
total_H3K27ac <- n_distinct(annotated_H3K27ac_ext200$Peakid)
total_H3K9me3 <- n_distinct(annotated_H3K9me3_ext200$Peakid)

family_counts <- family_counts %>% 
  mutate(not_H3K27ac=total_H3K27ac - n_H3K27ac,
         not_H3K9me3=total_H3K9me3 - n_H3K9me3)



```


```{r}
run_family_fisher <- function(df,
                              a = "n_H3K27ac",
                              b = "not_H3K27ac",
                              c = "n_H3K9me3",
                              d = "not_H3K9me3",
                              family_col = "repFamily") {

  res <- lapply(seq_len(nrow(df)), function(i) {

    x <- df[i, ]

    tab <- matrix(
      c(x[[a]], x[[b]],
        x[[c]], x[[d]]),
      nrow = 2,
      byrow = TRUE
    )

    ft <- fisher.test(tab)

    data.frame(
      repFamily = x[[family_col]],
      odds_ratio = as.numeric(ft$estimate),
      conf_low = ft$conf.int[1],
      conf_high = ft$conf.int[2],
      p_value = ft$p.value
    )
  })

  out <- do.call(rbind, res)

  out$FDR <- p.adjust(out$p_value, method = "BH")

  out
}
run_name_fisher <- function(df,
                              a = "n_H3K27ac",
                              b = "not_H3K27ac",
                              c = "n_H3K9me3",
                              d = "not_H3K9me3",
                              family_col = "repName") {

  res <- lapply(seq_len(nrow(df)), function(i) {

    x <- df[i, ]

    tab <- matrix(
      c(x[[a]], x[[b]],
        x[[c]], x[[d]]),
      nrow = 2,
      byrow = TRUE
    )

    ft <- fisher.test(tab)

    data.frame(
      repName = x[[family_col]],
      odds_ratio = as.numeric(ft$estimate),
      conf_low = ft$conf.int[1],
      conf_high = ft$conf.int[2],
      p_value = ft$p.value
    )
  })

  out <- do.call(rbind, res)

  out$FDR <- p.adjust(out$p_value, method = "BH")

  out
}
```


```{r}
 enrichment_ratio_results <- run_family_fisher(family_counts)
```


```{r}
ggplot(enrichment_ratio_results, aes(x = (odds_ratio), y = -log10(FDR),label = repFamily)) +
  geom_point(aes(color = odds_ratio > 1), size = 3) +
   # geom_text_repel(data = subset(SVA_results, FDR < 0.05)) +
  geom_text_repel(size=3, max.overlaps = Inf)+
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  labs(
    x = "(Odds Ratio)",
    y = "-log10(FDR)",
    title = "H3K27ac v H3K9me3 enrichment"
  ) +
  theme_classic() 
```
```{r}
results_display <- enrichment_ratio_results %>%
 
  # 2. Add log2 odds ratio
  mutate(log2OR = log2(odds_ratio)) %>%
  
  # 3. Add enrichment/depletion direction
  mutate(direction = case_when(
    odds_ratio > 1 ~ "enriched",
    odds_ratio < 1 ~ "depleted",
    TRUE           ~ "neutral"
  )) %>%
  
  # 4. Flag significant
  mutate(significant = FDR < 0.05) %>%
  
  # Optional: arrange for readability
  arrange(desc(log2OR))

# ---- Create interactive datatable ----
datatable(
  results_display,
  rownames = FALSE,
  filter = 'top',       # add filter/search boxes
  options = list(
    pageLength = 10,
    autoWidth = TRUE,
    scrollX = TRUE
  )
) %>%
  # Conditional coloring by direction
  formatStyle(
    'direction',
    target = 'row',
    backgroundColor = styleEqual(
      c('enriched', 'depleted'),
      c('#FFDD99', '#99CCFF')  # enriched = light orange, depleted = light blue
    )
  ) %>%
  # Bold significant rows
  formatStyle(
    'significant',
    fontWeight = styleEqual(TRUE, 'bold')
  ) %>%
  # Round numeric columns for readability
  formatRound(columns = c('odds_ratio','log2OR','FDR'), digits = 2)
```

### Rep Name


```{r}

H3K27ac_name_count <- annotated_H3K27ac_ext200 %>% 
  dplyr::select(Peakid, repName,cluster) %>% 
  na.omit(repName) %>% 
  separate_longer_delim(repName,delim = ";") %>% 
 dplyr::distinct(Peakid, repName) %>%   # 🔑 KEY STEP
  dplyr::count(repName, name = "n_H3K27ac")


H3K9me3_name_count <- annotated_H3K9me3_ext200 %>% 
  dplyr::select(Peakid, repName,cluster) %>% 
  na.omit(repName) %>% 
  separate_longer_delim(repName,delim = ";") %>% 
 dplyr::distinct(Peakid, repName) %>%   # 🔑 KEY STEP
  dplyr::count(repName, name = "n_H3K9me3")



name_counts <- full_join(
  H3K27ac_name_count,
  H3K9me3_name_count,
  by = "repName"
) %>%
  tidyr::replace_na(list(n_H3K27ac = 0, n_H3K9me3 = 0))

### adding in totals and totals without
total_H3K27ac <- n_distinct(annotated_H3K27ac_ext200$Peakid)
total_H3K9me3 <- n_distinct(annotated_H3K9me3_ext200$Peakid)

name_counts <- name_counts %>% 
  mutate(not_H3K27ac=total_H3K27ac - n_H3K27ac,
         not_H3K9me3=total_H3K9me3 - n_H3K9me3) %>% 
  dplyr::filter(n_H3K27ac + n_H3K9me3>15)




```


```{r}
 Name_enrichment_ratio_results <- run_name_fisher(name_counts)
```



```{r plot name}
ggplot(Name_enrichment_ratio_results, aes(x = (odds_ratio), y = -log10(FDR),label = repName)) +
  geom_point(aes(color = odds_ratio > 1), size = 3) +
   geom_text_repel(data = subset(Name_enrichment_ratio_results, FDR < 0.01)) +
  # geom_text_repel(size=3, max.overlaps = Inf)+
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  labs(
    x = "(Odds Ratio)",
    y = "-log10(FDR)",
    title = "H3K27ac v H3K9me3 enrichment"
  ) +
  theme_classic() 
```


```{r table name}
results_display <- Name_enrichment_ratio_results %>%
 
  # 2. Add log2 odds ratio
  mutate(log2OR = log2(odds_ratio)) %>%
  
  # 3. Add enrichment/depletion direction
  mutate(direction = case_when(
    odds_ratio > 1 ~ "enriched",
    odds_ratio < 1 ~ "depleted",
    TRUE           ~ "neutral"
  )) %>%
  
  # 4. Flag significant
  mutate(significant = FDR < 0.05) %>%
  
  # Optional: arrange for readability
  arrange(desc(log2OR))

# ---- Create interactive datatable ----
datatable(
  results_display,
  rownames = FALSE,
  filter = 'top',       # add filter/search boxes
  options = list(
    pageLength = 10,
    autoWidth = TRUE,
    scrollX = TRUE
  )
) %>%
  # Conditional coloring by direction
  formatStyle(
    'direction',
    target = 'row',
    backgroundColor = styleEqual(
      c('enriched', 'depleted'),
      c('#FFDD99', '#99CCFF')  # enriched = light orange, depleted = light blue
    )
  ) %>%
  # Bold significant rows
  formatStyle(
    'significant',
    fontWeight = styleEqual(TRUE, 'bold')
  ) %>%
  # Round numeric columns for readability
  formatRound(columns = c('odds_ratio','log2OR','FDR'), digits = 2)
```




