---
title: "H3K27ac TF enrichment"
author: "Renee Matthews"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```


```{r packages}
library(tidyverse)
library(GenomicRanges)
library(plyranges)
library(genomation)
library(readr)
library(rtracklayer)
library(stringr)
library(DT)

```

### Summit calls method 1  


```{r loading motif data Set2}

H3K27ac_Set2_sea_disc_out <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400/sea_disc_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set2_sea_known <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400/sea_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set2_xstreme <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400/xstreme.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="all") %>% slice_head(n = length(.$ID)-3)


H3K27ac_Set2_tomtom <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400/streme_tomtom_out/tomtom.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

test_bind <- bind_rows(H3K27ac_Set2_sea_disc_out, H3K27ac_Set2_sea_known) %>% 
  dplyr::select(DB:ENR_RATIO) %>% 
  group_by(ID,ALT_ID, ENR_RATIO) %>% distinct()


```

```{r loading motif data Set3}

H3K27ac_Set3_sea_disc_out <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400/sea_disc_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set3_sea_known <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400/sea_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set3_xstreme <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400/xstreme.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="all") %>% slice_head(n = length(.$ID)-3)


H3K27ac_Set3_tomtom <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400/streme_tomtom_out/tomtom.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

test_bind3 <-bind_rows(H3K27ac_Set3_sea_disc_out, H3K27ac_Set3_sea_known) %>%
  dplyr::select(DB:ENR_RATIO) %>% 
  group_by(ID,ALT_ID) %>% 
  distinct()


```


```{r  making data sets}
H3K27ac_Set2_data <- H3K27ac_Set2_xstreme %>% 
  dplyr::select(RANK:CLUSTER,ID:CONSENSUS,EVALUE,SIM_MOTIF,MOTIF_URL) %>% 
  mutate(MOTIF_URL=str_replace(MOTIF_URL,"https://jaspar2024.elixir.no/matrix/","")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF)) %>% 
  left_join(test_bind) %>% 
  mutate(diff_per=`TP%` -`FP%`)

H3K27ac_Set3_data <- H3K27ac_Set3_xstreme %>% 
  dplyr::select(RANK:CLUSTER,ID:CONSENSUS,EVALUE,SIM_MOTIF,MOTIF_URL) %>% 
  mutate(MOTIF_URL=str_replace(MOTIF_URL,"https://jaspar2024.elixir.no/matrix/","")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF)) %>% 
  left_join(test_bind3, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(diff_per=`TP%` -`FP%`)

```


```{r}

H3K27ac_Set2_data %>% 
  dplyr::filter(ENR_RATIO>1.2) %>% 
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*2), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./2,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1, Enrichment ratio >1.2"))

H3K27ac_Set3_data %>% 
  dplyr::filter(ENR_RATIO>1.1) %>%
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*1), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1, Enrichment ratio > 1.1"))

```

```{r enrichment by cluster}

H3K27ac_Set2_data %>% 
  dplyr::filter(ENR_RATIO>1.2) %>% 
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*2), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./2,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1, Enrichment ratio >1.2"))

H3K27ac_Set3_data %>% 
  dplyr::filter(ENR_RATIO>1.1) %>%
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*1), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1, Enrichment ratio > 1.1"))

```  



```{r enrichment ratio dispersion}
H3K27ac_Set2_data %>% 
  ggplot(., aes (x= ENR_RATIO)) +
  geom_density()+
  # geom_point(aes(x=`TP%`*2), size =4)+
  # scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./2,name="Percent of peaks with motif"))+
  theme_classic()+
  # ylab("Enriched TF motif")+
  ggtitle(paste("Span of enrichment ratios for Set2"))


H3K27ac_Set3_data %>% 
  ggplot(., aes (x= ENR_RATIO)) +
  geom_density()+
  theme_classic()+
  ggtitle(paste("Span of enrichment ratios for Set3"))


H3K27ac_Set3_data %>% 
  ggplot(., aes (x= ENR_RATIO)) +
  geom_density()+
  theme_classic()+
  ggtitle(paste("Span of enrichment ratios for Set3"))+
  coord_cartesian(xlim=c(0,6))
```


```{r}

ggVennDiagram::ggVennDiagram(list("H3K27ac_Set2"=H3K27ac_Set2_data$motif_name,"H3K27ac_Set3"=H3K27ac_Set3_data$motif_name))+
  ggtitle("H3K27ac motif overlap")+
  coord_cartesian(clip = "off") +
  theme(
    plot.margin = margin(20, 60, 20, 60)  # top, right, bottom, left
  )
  
```

```{r method1 list}
# test_bind
# xstreme_rank_bind
DT::datatable((H3K27ac_Set2_data %>% 
  dplyr::select(RANK,CLUSTER,ID,ALT_ID,EVALUE, CONSENSUS)),
  rownames = FALSE,
  caption = htmltools::tags$caption(
    style = "caption-side: top; text-align: left; font-weight: bold;",
    "Method 1: Set 2 H3K27ac"
  ),
  filter = 'top',       # add filter/search boxes
  options = list(
    pageLength = 10,
    autoWidth = FALSE,
    scrollX = TRUE)) 

DT::datatable((H3K27ac_Set3_data %>% 
  dplyr::select(RANK,CLUSTER,ID,ALT_ID,EVALUE, CONSENSUS.x)),
  rownames = FALSE,
  caption = htmltools::tags$caption(
    style = "caption-side: top; text-align: left; font-weight: bold;",
    "Method 1: Set 3 H3K27ac"
  ),
  filter = 'top',       # add filter/search boxes
  options = list(
    pageLength = 10,
    autoWidth = FALSE,
    scrollX = TRUE)) 


```

```{r set 2 by facet}
H3K27ac_Set2_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(RANK <15~"A",
                              log10Evalue >15 & log10Evalue <40~"B",
            log10Evalue>40~"C")) %>% 
  dplyr::filter(Facets=="A") %>% 
    ggplot(., aes (y= reorder(motif_name, log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
   geom_point(aes(x=ENR_RATIO*40, color=ENR_RATIO), size =4)+
  scale_x_continuous(expand = c(0, .125),
  sec.axis = sec_axis(~ . /40, name = "Enrichment Ratio"))+
 
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1\n top Enrichment Ratio by Cluster H3K27ac"))



H3K27ac_Set2_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(RANK <15~"A",
                              log10Evalue >15 & log10Evalue <40~"B",
            log10Evalue>40~"C")) %>% 
  dplyr::filter(Facets=="B") %>% 
     ggplot(., aes (y= reorder(motif_name, log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*10, color=ENR_RATIO), size =4)+
  
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . / 10, name = "Enrichment Ratio")
)+
  scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma") +
  tidytext::scale_y_reordered()+
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1\n top Enrichment Ratio by Cluster H3K27ac"))



H3K27ac_Set2_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
     mutate(Facets=case_when(RANK <15~"A",
                              log10Evalue >15 & log10Evalue <40~"B",
            log10Evalue>40~"C")) %>% 
  dplyr::filter(Facets=="C") %>% 
     ggplot(., aes (y= reorder(motif_name, log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*.8, color=ENR_RATIO), size =4)+
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . / .8, name = "Enrichment Ratio")
)+
  scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma") +
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1\n top Enrichment Ratio by Cluster H3K27ac"))
```

```{r set 3 by facet}
H3K27ac_Set3_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(log10Evalue >10~"A",
                              log10Evalue <10 & log10Evalue >5~"B",
            log10Evalue<5~"C")) %>% 
  dplyr::filter(Facets=="A") %>% 
    ggplot(., aes (y= reorder(motif_name, log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*10, color=ENR_RATIO), size =4)+
  geom_vline(
  xintercept = 1*10,
  linetype = "dotted",
  linewidth = 1, color="red")+
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . / 10, name = "Enrichment Ratio")
)+
   scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma") +
  tidytext::scale_y_reordered()+
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1\n top Enrichment Ratio by Cluster H3K27ac"))



H3K27ac_Set3_data %>% 
  dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(log10Evalue >10~"A",
                              log10Evalue <10 & log10Evalue >5~"B",
            log10Evalue<5~"C")) %>% 
  dplyr::filter(Facets=="B") %>% 
    ggplot(., aes (y= tidytext::reorder_within(motif_name, log10Evalue, Facets))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*5, color=ENR_RATIO), size =4)+
  geom_vline(
  xintercept = 1*5,
  linetype = "dotted",
  linewidth = 1, color="red")+
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . / 5, name = "Enrichment Ratio")
)+ scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma"
  ) +
  tidytext::scale_y_reordered()+
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1\n top Enrichment Ratio by Cluster H3K27ac"))



H3K27ac_Set3_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(log10Evalue >10~"A",
                              log10Evalue <10 & log10Evalue >5~"B",
            log10Evalue<5~"C")) %>% 
  dplyr::filter(Facets=="C") %>% 
    ggplot(., aes (y= tidytext::reorder_within(motif_name, log10Evalue, Facets))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*.05,color= pmin(ENR_RATIO, 5)), size =4)+
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . /.05, name = "Enrichment Ratio")
)+
   scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma"
  ) +
  tidytext::scale_y_reordered()+
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1\n top Enrichment Ratio by Cluster H3K27ac"))


```




### Summit calls method 2  

```{r loading motif data Set2 met2}

H3K27ac_Set2_met2_sea_disc_out <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400_alt/sea_disc_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set2_met2_sea_known <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400_alt/sea_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set2_met2_xstreme <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400_alt/xstreme.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="all") %>% slice_head(n = length(.$ID)-3)


H3K27ac_Set2_met2_tomtom <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400_alt/streme_tomtom_out/tomtom.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

test_bind_met2 <- bind_rows(H3K27ac_Set2_met2_sea_disc_out, H3K27ac_Set2_met2_sea_known) %>% 
  dplyr::select(DB:ENR_RATIO) %>% 
  group_by(ID,ALT_ID, ENR_RATIO) %>% distinct()


```

```{r loading motif data Set3_met2}

H3K27ac_Set3_met2_sea_disc_out <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400_alt/sea_disc_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set3_met2_sea_known <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400_alt/sea_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set3_met2_xstreme <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400_alt/xstreme.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="all") %>% slice_head(n = length(.$ID)-3)


H3K27ac_Set3_met2_tomtom <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400_alt/streme_tomtom_out/tomtom.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

test_bind3_met2 <-bind_rows(H3K27ac_Set3_met2_sea_disc_out, H3K27ac_Set3_met2_sea_known) %>%
  dplyr::select(DB:ENR_RATIO) %>% 
  group_by(ID,ALT_ID) %>% 
  distinct()


```


```{r  making data sets met2}
H3K27ac_Set2_data_met2 <- H3K27ac_Set2_met2_xstreme %>% 
  dplyr::select(RANK:CLUSTER,ID:CONSENSUS,EVALUE,SIM_MOTIF,MOTIF_URL) %>% 
  mutate(MOTIF_URL=str_replace(MOTIF_URL,"https://jaspar2024.elixir.no/matrix/","")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF)) %>% 
  left_join(test_bind_met2) %>% 
  mutate(diff_per=`TP%` -`FP%`)

H3K27ac_Set3_data_met2 <- H3K27ac_Set3_met2_xstreme %>% 
  dplyr::select(RANK:CLUSTER,ID:CONSENSUS,EVALUE,SIM_MOTIF,MOTIF_URL) %>% 
  mutate(MOTIF_URL=str_replace(MOTIF_URL,"https://jaspar2024.elixir.no/matrix/","")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF)) %>% 
  left_join(test_bind3_met2, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(diff_per=`TP%` -`FP%`)

```

```{r met2 list}
# test_bind
# xstreme_rank_bind
DT::datatable((H3K27ac_Set2_data_met2 %>% 
  dplyr::select(RANK,CLUSTER,ID,ALT_ID,EVALUE, CONSENSUS)),
  rownames = FALSE,
  caption = htmltools::tags$caption(
    style = "caption-side: top; text-align: left; font-weight: bold;",
    "Method 2: Set 2 H3K27ac"
  ),
  filter = 'top',       # add filter/search boxes
  options = list(
    pageLength = 10,
    autoWidth = FALSE,
    scrollX = TRUE)) 

DT::datatable((H3K27ac_Set3_data_met2 %>% 
  dplyr::select(RANK,CLUSTER,ID,ALT_ID,EVALUE, CONSENSUS.x)),
  rownames = FALSE,
  caption = htmltools::tags$caption(
    style = "caption-side: top; text-align: left; font-weight: bold;",
    "Method 2: Set 3 H3K27ac"
  ),
  filter = 'top',       # add filter/search boxes
  options = list(
    pageLength = 10,
    autoWidth = FALSE,
    scrollX = TRUE)) 


```


### Summit calls method 3
```{r loading motif data Set2 met3}

H3K27ac_Set2_met3_sea_disc_out <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400_alt_concat/sea_disc_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set2_met3_sea_known <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400_alt_concat/sea_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set2_met3_xstreme <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400_alt_concat/xstreme.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="all") %>% slice_head(n = length(.$ID)-3)


H3K27ac_Set2_met3_tomtom <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set2_400_alt_concat/streme_tomtom_out/tomtom.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

test_bind_met3 <- bind_rows(H3K27ac_Set2_met3_sea_disc_out, H3K27ac_Set2_met3_sea_known) %>% 
  dplyr::select(DB:ENR_RATIO) %>% 
  group_by(ID,ALT_ID, ENR_RATIO) %>% distinct()


```

```{r loading motif data Set3_met3}

H3K27ac_Set3_met3_sea_disc_out <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400_alt_concat/sea_disc_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set3_met3_sea_known <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400_alt_concat/sea_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)

H3K27ac_Set3_met3_xstreme <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400_alt_concat/xstreme.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="all") %>% slice_head(n = length(.$ID)-3)


H3K27ac_Set3_met3_tomtom <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K27ac/H3K27ac_set3_400_alt_concat/streme_tomtom_out/tomtom.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

test_bind3_met3 <-bind_rows(H3K27ac_Set3_met3_sea_disc_out, H3K27ac_Set3_met3_sea_known) %>%
  dplyr::select(DB:ENR_RATIO) %>% 
  group_by(ID,ALT_ID) %>% 
  distinct()


```


```{r  making data sets met3}
H3K27ac_Set2_data_met3 <- H3K27ac_Set2_met3_xstreme %>% 
  dplyr::select(RANK:CLUSTER,ID:CONSENSUS,EVALUE,SIM_MOTIF,MOTIF_URL) %>% 
  mutate(MOTIF_URL=str_replace(MOTIF_URL,"https://jaspar2024.elixir.no/matrix/","")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF)) %>% 
  left_join(test_bind_met3) %>% 
  mutate(diff_per=`TP%` -`FP%`)

H3K27ac_Set3_data_met3 <- H3K27ac_Set3_met3_xstreme %>% 
  dplyr::select(RANK:CLUSTER,ID:CONSENSUS,EVALUE,SIM_MOTIF,MOTIF_URL) %>% 
  mutate(MOTIF_URL=str_replace(MOTIF_URL,"https://jaspar2024.elixir.no/matrix/","")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF)) %>% 
  left_join(test_bind3_met3, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(diff_per=`TP%` -`FP%`)

```
```{r met3 list}
# test_bind
# xstreme_rank_bind
DT::datatable((H3K27ac_Set2_data_met3 %>% 
  dplyr::select(RANK,CLUSTER,ID,ALT_ID,EVALUE, CONSENSUS)),
  rownames = FALSE,
  caption = htmltools::tags$caption(
    style = "caption-side: top; text-align: left; font-weight: bold;",
    "Method 3: Set 2 H3K27ac"
  ),
  filter = 'top',       # add filter/search boxes
  options = list(
    pageLength = 10,
    autoWidth = FALSE,
    scrollX = TRUE)) 

DT::datatable((H3K27ac_Set3_data_met3 %>% 
  dplyr::select(RANK,CLUSTER,ID,ALT_ID,EVALUE, CONSENSUS.x)),
  rownames = FALSE,
  caption = htmltools::tags$caption(
    style = "caption-side: top; text-align: left; font-weight: bold;",
    "Method 3: Set 3 H3K27ac"
  ),
  filter = 'top',       # add filter/search boxes
  options = list(
    pageLength = 10,
    autoWidth = FALSE,
    scrollX = TRUE)) 


```

```{r direct compare}

toplist_direct_set2 <- list("set2_met1"=H3K27ac_Set2_data$ALT_ID,
"set2_met2"=H3K27ac_Set2_data_met2$ALT_ID,
"set2_met3"=H3K27ac_Set2_data_met3$ALT_ID)

toplist_direct_set3 <- list("set3_met1"=H3K27ac_Set3_data$ALT_ID,
"set3_met2"=H3K27ac_Set3_data_met2$ALT_ID,
"set3_met3"=H3K27ac_Set3_data_met3$ALT_ID)



```

```{r}
 Shared_motifs_set2 <- Reduce(intersect, toplist_direct_set2)
ggVennDiagram::ggVennDiagram(toplist_direct_set2)+scale_fill_gradient(
    low = "white",
    high = "blue"
  )

 Shared_motifs_set3 <- Reduce(intersect, toplist_direct_set3)
ggVennDiagram::ggVennDiagram(toplist_direct_set3)+scale_fill_gradient(
    low = "white",
    high = "red"
  )
```




