---
title: "H3K27ac and cis Regulatory Elements"
author: "Renee Matthews"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```

```{r package loading}
library(tidyverse)
library(GenomicRanges)
library(plyranges)
library(genomation)
library(readr)
library(rtracklayer)
library(stringr)
library(ggrepel)
library(DT)
library(readxl)
library(ChIPseeker)
```


```{r SCREEN all enhancers, eval=FALSE}
SCREEN_hg38_cCREs <- import(
  "data/Bed_exports/cisRE/GRCh38-cCREs.bed",
  format = "BED",
  extraCols = c(
    DHS_ID = "character",
    cCRE_ID = "character",
    cCRE_class = "character"
  )
)

strand(SCREEN_hg38_cCREs) <- "*"
cCRE_split_1 <- split(SCREEN_hg38_cCREs, SCREEN_hg38_cCREs$cCRE_class)
names(cCRE_split)

outdir <- "data/Bed_exports/cisRE/by_class"
dir.create(outdir, showWarnings = FALSE, recursive = TRUE)

for (cls in names(cCRE_split_1)) {
  export(
    cCRE_split_1[[cls]],
    con = file.path(outdir, paste0("SCREEN_hg38_", cls, ".bed")),
    format = "BED"
  )
}
```


```{r SCREEN heartLV female 53, eval=FALSE}
SCREEN_heart_hg38_cCREs <- import(
  "data/Other_paper_data/SCREEN_LVHEART_F_53_ENCFF417JSF_ENCFF651XRK_ENCFF320IPT_ENCFF440RUS.bed",
  format = "BED",
  extraCols = c(
    DHS_ID = "character",
    cCRE_ID = "character",
    cCRE_class = "character"
  )
)

strand(SCREEN_heart_hg38_cCREs) <- "*"
cCRE_split <- split(SCREEN_heart_hg38_cCREs, SCREEN_heart_hg38_cCREs$cCRE_ID)
names(cCRE_split)

outdir <- "data/Bed_exports/cisRE/heart_by_class"
dir.create(outdir, showWarnings = FALSE, recursive = TRUE)

for (cls in names(cCRE_split)) {
  export(
    cCRE_split[[cls]],
    con = file.path(outdir, paste0("SCREEN_heartLV_", cls, ".bed")),
    format = "BED"
  )
}
```
H3K27ac set enrichment
```{r data loading}
SCREEN_hg38_cCREs <- import(
  "data/Bed_exports/cisRE/GRCh38-cCREs.bed",
  format = "BED",
  extraCols = c(
    DHS_ID = "character",
    cCRE_ID = "character",
    cCRE_class = "character"))

H3K27ac_anno_ROIs <- readRDS("data/motif_lists/H3K27ac_annotated_peaks.RDS")
H3K27ac_toplist <- readRDS( "data/DER_data/H3K27ac_toplist.RDS")
H3K27ac_toptable_list <- bind_rows(H3K27ac_toplist, .id = "group")
## Loading single summit locations and adding in 
H3K27ac_summit_gr <- readRDS("data/RDS_files/H3K27ac_complete_summit_gr.RDS")

##assigning Peakid as name of summit region
 mcols(H3K27ac_summit_gr)$name <- mcols(H3K27ac_summit_gr)$Peakid
 

## Creating a lookup file if needed
H3K27ac_lookup <- imap_dfr(H3K27ac_anno_ROIs[1:3], ~
  tibble(Peakid = .x@anno$Peakid, cluster = .y)
)
# cRE_color_palette <- c("#E64B35FF", "#4DBBD5FF", "#00A087FF" ,"#3C5488FF", "#F39B7FFF", "#8491B4FF", "#91D1C2FF", "#DC0000FF", "#7E6148FF", "#B09C85FF" )
# 
# 
# cCRE_discrete_colors <- paletteer_d("ggsci::default_aaas")


```




```{r}
H3K27ac_cre_hits <- findOverlaps(H3K27ac_summit_gr, SCREEN_hg38_cCREs, ignore.strand = TRUE)

H3K27ac_cre_df <- tibble(
  Peakid=mcols(H3K27ac_summit_gr)$Peakid[queryHits(H3K27ac_cre_hits)],
  cluster   = mcols(H3K27ac_summit_gr)$cluster[queryHits(H3K27ac_cre_hits)],
  cCRE_ID   = mcols(SCREEN_hg38_cCREs)$cCRE_ID[subjectHits(H3K27ac_cre_hits)],
  cCRE_class= mcols(SCREEN_hg38_cCREs)$cCRE_class[subjectHits(H3K27ac_cre_hits)])


```

```{r color fill}
scale_fill_cCREs <-  function(...){
  ggplot2:::manual_scale(
    'fill', 
    values = setNames(c( "#E64B35FF", "#4DBBD5FF", "#00A087FF" ,"#3C5488FF", "#F39B7FFF", "#8491B4FF", "#91D1C2FF", "#DC0000FF", "#7E6148FF", "#B09C85FF" ), c(unique(H3K27ac_cre_df$cCRE_class),"NA")), 
    ...
  )
}


```

```{r}
H3K27ac_cre_anno <- H3K27ac_anno_ROIs$all_H3K27ac %>% as.data.frame() %>% 
  left_join(.,H3K27ac_cre_df ) %>% 
  dplyr::select(Peakid,cluster, cCRE_ID,cCRE_class) %>% 
  mutate(cluster = if_else(is.na(cluster), "not_assigned", cluster), 
         cCRE_ID=if_else(is.na(cCRE_ID),"NA",cCRE_ID),
         cCRE_class=if_else(is.na(cCRE_class),"NA",cCRE_class))

H3K27ac_cre_counts <- H3K27ac_cre_anno %>% 
  count(cluster, cCRE_class) %>% 
  group_by(cluster) %>% 
  mutate(percent= n/sum(n))

 ggplot(H3K27ac_cre_counts, aes(x = cluster, y = percent, fill = cCRE_class)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(
    y = "Proportion of ROIs",
    x = "Set",
    fill = "cCRE class"
  ) +
  theme_classic()+
     ggtitle("Hg38 all cCREs")+scale_fill_cCREs()
   
```

```{r}

SCREEN_heart_hg38_cCREs <- import(
  "data/Other_paper_data/SCREEN_LVHEART_F_53_ENCFF417JSF_ENCFF651XRK_ENCFF320IPT_ENCFF440RUS.bed",
  format = "BED",
  extraCols = c(
    DHS_ID = "character",
    cCRE_ID = "character",
    cCRE_class = "character"))
SCREEN_heart_hg38_cCREs %>% as.data.frame() %>% distinct(cCRE_ID)


H3K27ac_heart_cre_hits <- findOverlaps(H3K27ac_summit_gr, SCREEN_heart_hg38_cCREs, ignore.strand = TRUE)

H3K27ac_heart_cre_df <- tibble(
  Peakid=mcols(H3K27ac_summit_gr)$Peakid[queryHits(H3K27ac_heart_cre_hits)],
  cluster   = mcols(H3K27ac_summit_gr)$cluster[queryHits(H3K27ac_heart_cre_hits)],
  cCRE_ID   = mcols(SCREEN_hg38_cCREs)$cCRE_ID[subjectHits(H3K27ac_heart_cre_hits)],
  cCRE_class= mcols(SCREEN_hg38_cCREs)$cCRE_class[subjectHits(H3K27ac_heart_cre_hits)])

H3K27ac_heart_cre_anno <- H3K27ac_anno_ROIs$all_H3K27ac %>% as.data.frame() %>% 
  left_join(.,H3K27ac_heart_cre_df ) %>% 
  dplyr::select(Peakid,cluster, cCRE_ID,cCRE_class) %>% 
  mutate(cluster = if_else(is.na(cluster), "not_assigned", cluster), 
         cCRE_ID=if_else(is.na(cCRE_ID),"NA",cCRE_ID),
         cCRE_class=if_else(is.na(cCRE_class),"NA",cCRE_class))

```

```{r heart cre plot}
H3K27ac_heart_cre_counts <- H3K27ac_heart_cre_anno %>% 
  count(cluster, cCRE_class) %>% 
  group_by(cluster) %>% 
  mutate(percent= n/sum(n))

 ggplot(H3K27ac_heart_cre_counts, aes(x = cluster, y = percent, fill = cCRE_class)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(
    yy = "Proportion of ROIs",
    x = "Set",
    fill = "cCRE class"
  ) +
  theme_classic()+
     ggtitle("Heart-left ventricle cCREs")+scale_fill_cCREs()
   
   
```
```{r}
# all.equal(SCREEN_heart_hg38_cCREs, SCREEN_hg38_cCREs)
# 
# identical(
#   dplyr::arrange(SCREEN_heart_hg38_cCREs, across(everything())),
#   dplyr::arrange(SCREEN_hg38_cCREs, across(everything()))
# )
# 
# dplyr::left_join((SCREEN_heart_hg38_cCREs %>% as.data.frame()),(SCREEN_hg38_cCREs %>% as.data.frame())                 )
```

