---
title: "H3K9me3 TF enrichment"
author: "Renee Matthews"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```


```{r packages}
library(tidyverse)
library(GenomicRanges)
library(plyranges)
library(genomation)
library(readr)
library(rtracklayer)
library(stringr)
library(readxl)

```

```{r loading motif data Set2}

H3K9me3_Set2_sea_disc_out <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K9me3/H3K9me3_set2_400/sea_disc_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)

H3K9me3_Set2_sea_known <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K9me3/H3K9me3_set2_400/sea_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)

H3K9me3_Set2_xstreme <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K9me3/H3K9me3_set2_400/xstreme.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="all") %>% slice_head(n = length(.$ID)-3)


H3K9me3_Set2_tomtom <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K9me3/H3K9me3_set2_400/streme_tomtom_out/tomtom.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

test_bind <-bind_rows(H3K9me3_Set2_sea_disc_out, H3K9me3_Set2_sea_known) %>% 
  dplyr::select(DB:ENR_RATIO) %>% 
  group_by(ID,ALT_ID, ENR_RATIO) %>% distinct()


```

```{r loading motif data Set3}

H3K9me3_Set3_sea_disc_out <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K9me3/H3K9me3_set3_400/sea_disc_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)

H3K9me3_Set3_sea_known <-read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K9me3/H3K9me3_set3_400/sea_out/sea.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)

H3K9me3_Set3_xstreme <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K9me3/H3K9me3_set3_400/xstreme.tsv", delim = "\t", escape_double = FALSE,     trim_ws = TRUE) %>% mutate(source="all") %>% slice_head(n = length(.$ID)-3)


H3K9me3_Set3_tomtom <- read_delim("C:/Users/renee/Other_projects_data/DXR_data/H3K9me3/H3K9me3_set3_400/streme_tomtom_out/tomtom.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

test_bind3 <-
bind_rows(H3K9me3_Set3_sea_disc_out, H3K9me3_Set3_sea_known) %>% 
  dplyr::select(DB:ENR_RATIO) %>% 
  group_by(ID,ALT_ID) %>% 
  distinct()


```


```{r  making data sets}
H3K9me3_Set2_data <- H3K9me3_Set2_xstreme %>% 
  dplyr::select(RANK:CLUSTER,ID:CONSENSUS,EVALUE,SIM_MOTIF,MOTIF_URL) %>% 
  mutate(MOTIF_URL=str_replace(MOTIF_URL,"https://jaspar2024.elixir.no/matrix/","")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF)) %>% 
  left_join(test_bind, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(diff_per=`TP%` -`FP%`)

H3K9me3_Set3_data <- H3K9me3_Set3_xstreme %>% 
  dplyr::select(RANK:CLUSTER,ID:CONSENSUS,EVALUE,SIM_MOTIF,MOTIF_URL) %>% 
  mutate(MOTIF_URL=str_replace(MOTIF_URL,"https://jaspar2024.elixir.no/matrix/","")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF)) %>% 
  left_join(test_bind3, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(diff_per=`TP%` -`FP%`)

```


```{r}

# H3K9me3_Set3_data %>% 
#   group_by(CLUSTER) %>%
#   arrange(.,EVALUE) %>% 
#   slice_min(EVALUE, with_ties = FALSE) 
  
H3K9me3_Set2_data %>% 
  dplyr::filter(ENR_RATIO>1.2) %>% 
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
   mutate(Facets=case_when(log10Evalue>20~"A",
                          log10Evalue<20 & log10Evalue>4 ~"B",
                          TRUE ~ "C")) %>% 
   dplyr::filter(Facets=="A") %>% 
  # group_by(Facets) %>% tally()
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*2), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./2,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1,Top20, Enrichment ratio >1.2"))+
  facet_wrap(~Facets)

H3K9me3_Set2_data %>% 
  dplyr::filter(ENR_RATIO>1.2) %>% 
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
   mutate(Facets=case_when(log10Evalue>20~"A",
                          log10Evalue<20 & log10Evalue>4 ~"B",
                          TRUE ~ "C")) %>% 
   dplyr::filter(Facets=="B") %>% 
  # group_by(Facets) %>% tally()
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*2), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./2,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1 Enrichment ratio >1.2"))+
  facet_wrap(~Facets)

H3K9me3_Set2_data %>% 
  dplyr::filter(ENR_RATIO>1.2) %>% 
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
   mutate(Facets=case_when(log10Evalue>20~"A",
                          log10Evalue<20 & log10Evalue>4 ~"B",
                          TRUE ~ "C")) %>% 
   dplyr::filter(Facets=="C") %>% 
  # group_by(Facets) %>% tally()
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*2), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./2,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1 Enrichment ratio >1.2"))+
  facet_wrap(~Facets)


##-------------------------------------------------------------------

H3K9me3_Set3_data %>% 
  dplyr::filter(ENR_RATIO>1.2) %>%
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
  mutate(Facets=case_when(log10Evalue>30~"A",
                          log10Evalue<30 ~"B",
                          TRUE ~ "C")) %>% 
  # group_by(Facets) %>% tally()
  dplyr::filter(Facets=="A") %>% 
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*1), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1, Enrichment ratio > 1.2"))+
  facet_wrap(~Facets)


H3K9me3_Set3_data %>% 
  dplyr::filter(ENR_RATIO>1.2) %>%
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
  mutate(Facets=case_when(log10Evalue>30~"A",
                          log10Evalue<30 &log10Evalue>6 ~"B",
                          TRUE ~ "C")) %>% 
  # group_by(Facets) %>% tally()
  dplyr::filter(Facets=="B") %>% 
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*1), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1, Enrichment ratio > 1.2"))+
  facet_wrap(~Facets)

H3K9me3_Set3_data %>% 
  dplyr::filter(ENR_RATIO>1.2) %>%
  group_by(CLUSTER) %>% 
  slice_min(EVALUE, with_ties = FALSE) %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
  mutate(Facets=case_when(log10Evalue>30~"A",
                          log10Evalue<30 &log10Evalue>6 ~"B",
                          TRUE ~ "C")) %>% 
  # group_by(Facets) %>% tally()
  dplyr::filter(Facets=="C") %>% 
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=`TP%`*1), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1, Enrichment ratio > 1.2"))+
  facet_wrap(~Facets)
```


```{r enrichment ratio dispersion}
H3K9me3_Set2_data %>% 
  ggplot(., aes (x= ENR_RATIO)) +
  geom_density()+
  # geom_point(aes(x=`TP%`*2), size =4)+
  # scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./2,name="Percent of peaks with motif"))+
  theme_classic()+
  # ylab("Enriched TF motif")+
  ggtitle(paste("Span of enrichment ratios for Set2"))


H3K9me3_Set3_data %>% 
  ggplot(., aes (x= ENR_RATIO)) +
  geom_density()+
  theme_classic()+
  ggtitle(paste("Span of enrichment ratios for Set3"))



```
```{r set 2 by facet}
H3K9me3_Set2_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
  mutate(motif_name=case_when(motif_name=="TFAP2B"~paste0(motif_name,"_",RANK),
                              motif_name=="GCM2"~paste0(motif_name,"_",RANK),
                              TRUE~motif_name)) %>% 
    mutate(Facets=case_when(RANK <15~"A",
                              log10Evalue >15 & log10Evalue <40~"B",
            log10Evalue>40~"C")) %>% 
  dplyr::filter(Facets=="A") %>% 
    ggplot(., aes (y= reorder(motif_name, log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
   geom_point(aes(x=ENR_RATIO*5, color=ENR_RATIO), size =4)+
  scale_x_continuous(expand = c(0, .125),
  sec.axis = sec_axis(~ . /5, name = "Enrichment Ratio"))+
 scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma") +
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1\n top Enrichment Ratio by Cluster H3K9me3"))



H3K9me3_Set2_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(RANK <15~"A",
                              log10Evalue >15 & log10Evalue <40~"B",
            log10Evalue>40~"C")) %>% 
  dplyr::filter(Facets=="B") %>% 
     ggplot(., aes (y= reorder(motif_name, log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*10, color=ENR_RATIO), size =4)+
  
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . / 10, name = "Enrichment Ratio")
)+
  scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma") +
  tidytext::scale_y_reordered()+
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1\n top Enrichment Ratio by Cluster H3K9me3"))



H3K9me3_Set2_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
     mutate(Facets=case_when(RANK <15~"A",
                              log10Evalue >15 & log10Evalue <40~"B",
            log10Evalue>40~"C")) %>% 
  dplyr::filter(Facets=="C") %>% 
     ggplot(., aes (y= reorder(motif_name, log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*8, color=ENR_RATIO), size =4)+
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . / 8, name = "Enrichment Ratio")
)+
  scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma") +
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET2 enrichment over SET1\n top Enrichment Ratio by Cluster H3K9me3"))
```
```{r set 3 by facet}
H3K9me3_Set3_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(log10Evalue >20~"A",
          log10Evalue <20 & log10Evalue >10~"B",
         log10Evalue<10& log10Evalue<5~"C",
         TRUE~"D")) %>% 
  dplyr::filter(Facets=="A") %>% 
    ggplot(., aes (y= reorder(motif_name, log10Evalue))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*15, color=ENR_RATIO), size =4)+
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . /15, name = "Enrichment Ratio")
)+
   scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma") +
  tidytext::scale_y_reordered()+
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1\n top Enrichment Ratio by Cluster H3K9me3"))



H3K9me3_Set3_data %>% 
  dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(log10Evalue >20~"A",
          log10Evalue <20 & log10Evalue >10~"B",
         log10Evalue<10& log10Evalue<5~"C",
         TRUE~"D")) %>% 
  dplyr::filter(Facets=="B") %>% 
    ggplot(., aes (y= tidytext::reorder_within(motif_name, log10Evalue, Facets))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*5, color=ENR_RATIO), size =4)+
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . / 5, name = "Enrichment Ratio")
)+ scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma"
  ) +
  tidytext::scale_y_reordered()+
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1\n top Enrichment Ratio by Cluster H3K9me3"))



H3K9me3_Set3_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(log10Evalue >20~"A",
          log10Evalue <20 & log10Evalue >10~"B",
         log10Evalue<10& log10Evalue<5~"C",
         TRUE~"D")) %>% 
  dplyr::filter(Facets=="C") %>% 
    ggplot(., aes (y= tidytext::reorder_within(motif_name, log10Evalue, Facets))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*2,color= pmin(ENR_RATIO, 5)), size =4)+
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . /2, name = "Enrichment Ratio")
)+
   scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma"
  ) +
  tidytext::scale_y_reordered()+
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1\n top Enrichment Ratio by Cluster H3K9me3"))

H3K9me3_Set3_data %>% 
dplyr::filter(EVALUE<0.05) %>% 
   group_by(CLUSTER) %>% 
  slice_min(RANK, with_ties = FALSE) %>% 
  ungroup() %>% 
   mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>%
    mutate(Facets=case_when(log10Evalue >20~"A",
          log10Evalue <20 & log10Evalue >10~"B",
         log10Evalue<10& log10Evalue<5~"C",
         TRUE~"D")) %>% 
  dplyr::filter(Facets=="D") %>% 
    ggplot(., aes (y= tidytext::reorder_within(motif_name, log10Evalue, Facets))) +
  geom_col(aes(x=log10Evalue))+
  geom_point(aes(x=ENR_RATIO*2,color= pmin(ENR_RATIO, 5)), size =4)+
  scale_x_continuous(
  expand = c(0, .125),
  sec.axis = sec_axis(~ . /2, name = "Enrichment Ratio")
)+
   scale_color_viridis_c(
    name = "Enrichment Ratio",
    option = "plasma"
  ) +
  tidytext::scale_y_reordered()+
  facet_wrap(~Facets )+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("SET3 enrichment over SET1\n top Enrichment Ratio by Cluster H3K9me3"))
```


```{r}
plot_topnum_ratio_full <- function(df, title = NULL, signif.num = 0.05,top_num=20, color_limits = NULL){
  
  ### getting the name of the data frame for plotting
 if (is.null(title)) {
    title <- deparse(substitute(df))
 }
  
   

  ### Getting the data ready
  plot_df <- df %>%
    dplyr::filter(EVALUE < signif.num) %>%
    group_by(CLUSTER) %>%
    slice_min(RANK, with_ties = FALSE) %>%
    ungroup() %>%
    mutate(log10Evalue = -log10(EVALUE)) %>%
    arrange(desc(log10Evalue)) %>%
    mutate(motif_name_wrapped = stringr::str_wrap(motif_name, width = 10)) %>% 
     mutate(
    enr_shape = ifelse(ENR_RATIO > 1, "Enriched", "Depleted")) %>% 
    slice_head(., n=top_num)
#   
  scaler <- max(plot_df$log10Evalue) / max(plot_df$ENR_RATIO)

  ##plotting the data
   ggplot(plot_df, aes(y = reorder(motif_name_wrapped, log10Evalue))) +
    geom_col(aes(x = log10Evalue)) +
    geom_point(aes(x = ENR_RATIO* scaler, color = ENR_RATIO, shape = enr_shape), size = 4)+
    scale_x_continuous(
      expand = c(0, .125),
      sec.axis = sec_axis(~ . / scaler, name = "Enrichment Ratio")
    ) +
   scale_color_viridis_c(
  name = "Enrichment Ratio",
  option = "plasma",
  limits = color_limits,
  oob = scales::squish
)+
    scale_y_discrete(labels = function(x) stringr::str_wrap(gsub("__.*$", "", x), width = 10)) +
     scale_shape_manual(values = c("Enriched" = 16, "Depleted" = 17))+
    theme_classic() +
    ylab("Enriched TF motif") +
    ggtitle(paste(title, "-", top_num))
}


```




### RNA filtering  

```{r RNA filtering, fig.width=15}
RNA_full_toptable <-  readRDS("data/Other_paper_data/RNA_full_toptable.RDS")


RNA_expressed <- RNA_full_toptable %>% 
  dplyr::select(Entrez_ID, SYMBOL)

### had to add in a special filter to account for the :: in the names of the motifs
symbols <- str_to_upper(RNA_expressed$SYMBOL)

filtered_H3K9me3_Set3_data <- H3K9me3_Set3_data %>%
  ##create the motif-tokens column so I can keep names where there is a partial match in the RNA Symbols
  mutate(motif_tokens = str_split(str_to_upper(motif_name), "::")) %>%
  ##Because this is a list, now I need to filter using sapply, but then remove the motif token column
  filter(sapply(motif_tokens, function(x) any(x %in% symbols))) %>%
  select(-motif_tokens)


filtered_H3K9me3_Set2_data <- H3K9me3_Set2_data %>%
  mutate(motif_tokens = str_split(str_to_upper(motif_name), "::")) %>%
  filter(sapply(motif_tokens, function(x) any(x %in% symbols))) %>%
  select(-motif_tokens)


## binding both together to get them to set a global limit on the secondary axis using quantiles so color range is identical
global_combo <- bind_rows(filtered_H3K9me3_Set2_data, filtered_H3K9me3_Set3_data)

global_limits <-  quantile(global_combo$ENR_RATIO, probs = c(0.05, 0.95), na.rm = TRUE)
### plot seperately
  filt_A <- plot_topnum_ratio_full(filtered_H3K9me3_Set3_data,signif.num = 0.05, top_num = 10,color_limits = global_limits)
  
  filt_B <- plot_topnum_ratio_full(filtered_H3K9me3_Set2_data,signif.num = 0.05, top_num = 10,color_limits = global_limits)
 ## Good ole cowplot to align plots vertically 
  aligned_filt_plots <- cowplot::align_plots(filt_B, filt_A, align = "v", axis = "l")

cowplot::plot_grid(aligned_filt_plots[[1]],
          aligned_filt_plots[[2]],
          ncol = 2)

```



```{r}
KZFP_2026_list <- read_excel("data/Other_paper_data/human_protein_coding_KZFPs_Davis_natgen_2026.xlsx")

filtered_H3K9me3_Set2_data <- filtered_H3K9me3_Set2_data %>% 
  mutate(KZFP=if_else(motif_name %in%KZFP_2026_list$Label,"KZFP","not_KZFP"))
filtered_H3K9me3_Set3_data <- filtered_H3K9me3_Set3_data %>% 
  mutate(KZFP=if_else(motif_name %in%KZFP_2026_list$Label,"KZFP","not_KZFP"))

plot_topnum_ratio_KZFP <- function(df, title = NULL, signif.num = 0.05,top_num=20, color_limits = NULL){
  
  ### getting the name of the data frame for plotting
 if (is.null(title)) {
    title <- deparse(substitute(df))
 }
  
   

  ### Getting the data ready
  plot_df <- df %>%
    dplyr::filter(EVALUE < signif.num) %>%
    group_by(CLUSTER) %>%
    slice_min(RANK, with_ties = FALSE) %>%
    ungroup() %>%
    mutate(log10Evalue = -log10(EVALUE)) %>%
    arrange(desc(log10Evalue)) %>%
    mutate(motif_name_wrapped = stringr::str_wrap(motif_name, width = 10)) %>% 
     mutate(
    enr_shape = ifelse(ENR_RATIO > 1, "Enriched", "Depleted")) %>% 
    slice_head(., n=top_num)
#   
  scaler <- max(plot_df$log10Evalue) / max(plot_df$ENR_RATIO)

  ##plotting the data
   ggplot(plot_df, aes(y = reorder(motif_name_wrapped, log10Evalue))) +
    geom_col(aes(x = log10Evalue, fill=KZFP)) +
    geom_point(aes(x = ENR_RATIO* scaler, color = ENR_RATIO, shape = enr_shape), size = 4)+
    scale_x_continuous(
      expand = c(0, .125),
      sec.axis = sec_axis(~ . / scaler, name = "Enrichment Ratio")
    ) +
   scale_color_viridis_c(
  name = "Enrichment Ratio",
  option = "plasma",
  limits = color_limits,
  oob = scales::squish
)+
    scale_y_discrete(labels = function(x) stringr::str_wrap(gsub("__.*$", "", x), width = 10)) +
     scale_shape_manual(values = c("Enriched" = 16, "Depleted" = 17))+
    theme_classic() +
    ylab("Enriched TF motif") +
    ggtitle(paste(title, "-", top_num))
}
```


```{r}


## binding both together to get them to set a global limit on the secondary axis using quantiles so color range is identical
global_combo2 <- bind_rows(filtered_H3K9me3_Set2_data, filtered_H3K9me3_Set3_data)

global_limits2 <-  quantile(global_combo2$ENR_RATIO, probs = c(0.05, 0.95), na.rm = TRUE)
### plot seperately
  filt_A2 <- plot_topnum_ratio_KZFP(filtered_H3K9me3_Set3_data,signif.num = 0.05, top_num = 10,color_limits = global_limits2)
  
  filt_B2 <- plot_topnum_ratio_KZFP(filtered_H3K9me3_Set2_data,signif.num = 0.05, top_num = 10,color_limits = global_limits2)
 ## Good ole cowplot to align plots vertically 
  aligned_filt_plots <- cowplot::align_plots(filt_B2, filt_A2, align = "v", axis = "l")

cowplot::plot_grid(aligned_filt_plots[[1]],
          aligned_filt_plots[[2]],
          ncol = 2)
```

