---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

### QC and peak analysis

[Cut and Tag QC](https://reneeisnowhere.github.io/DXR_continue/multiQC_cut_tag.html)

[Peak Cutoffs](https://reneeisnowhere.github.io/DXR_continue/peak_cutoff.html)

[Peak Variants Analysis](https://reneeisnowhere.github.io/DXR_continue/peak_analysis.html)

[Peak Width](https://reneeisnowhere.github.io/DXR_continue/peak_width.html)

### Region selection and Differential analysis

[Pairwise differential analysis and PCA](https://reneeisnowhere.github.io/DXR_continue/final_analysis.html)

[Pairwise differential analysis and PCA: removing outliers](https://reneeisnowhere.github.io/DXR_continue/Outlier_removal.html)  
only H3K9me3 and H3K36me3

[Examining DERs by histone](https://reneeisnowhere.github.io/DXR_continue/DER_analysis.html)

[Cormotif analysis with all samples](https://reneeisnowhere.github.io/DXR_continue/Cormotif_analysis.html)  

[Cormotif analysis with removal of outliers](https://reneeisnowhere.github.io/DXR_continue/Cormotif_outlier_removal.html)  
only H3K9me3 and H3K36me3 were changed  
Also contains principal component contributions to variance in PCA for all histones


[Examining Cormotif results](https://reneeisnowhere.github.io/DXR_continue/Motif_cluster_analysis.html)  
Looking at finalized assigned cluster sets and characteristics

[Starting with repeatmasker overlaps](https://reneeisnowhere.github.io/DXR_continue/repeatmasker_data.html)


### Examining summit and ROI relationship  

[Collecting all summits](https://reneeisnowhere.github.io/DXR_continue/summit_files_processing.html)

[Investigating summits H3K27ac](https://reneeisnowhere.github.io/DXR_continue/H3K27ac_summit_processing.html) Uses double reduction method to cluster summits across treatment-time, then across all summits.

[Investigating summits H3K9me3](https://reneeisnowhere.github.io/DXR_continue/H3K9me3_summit_processing.html) Uses double reduction method to cluster summits across treatment-time, then across all summits.

[Investigating summits H3K36me3](https://reneeisnowhere.github.io/DXR_continue/H3K36me3_summit_processing.html) Uses double reduction method to cluster summits across treatment-time, then across all summits.

[Investigating summits H3K27me3](https://reneeisnowhere.github.io/DXR_continue/H3K27me3_summit_processing.html) Uses double reduction method to cluster summits across treatment-time, then across all summits.


[TE overlaps of ROI summits-H3K27ac](https://reneeisnowhere.github.io/DXR_continue/H3K27_TE_overlap.html)

[TE overlaps of ROI summits-H3K27ac extended regions](https://reneeisnowhere.github.io/DXR_continue/H3K27_TE_overlap_extend.html)

[TE overlaps of ROI summits-H3K27ac using alternate calls of summits](https://reneeisnowhere.github.io/DXR_continue/H3K27ac_summit_topqonly.html)

[TE overlaps of ROI summits-H3K9me3](https://reneeisnowhere.github.io/DXR_continue/H3K9me3_TE_overlap.html)  

[TE overlaps of ROI summits-H3K36me3](https://reneeisnowhere.github.io/DXR_continue/H3K36me3_TE_overlap.html)  


[TE overlaps of ROI summits-H3K27me3](https://reneeisnowhere.github.io/DXR_continue/H3K27me3_TE_overlap.html)  

###  TEs and ROIs

[Looking at TE families centered on TEs across histones](https://reneeisnowhere.github.io/DXR_continue/dual_histone_TE_investigation.html)  

[Looking at TE families centered on H3K27ac ROIs histones](https://reneeisnowhere.github.io/DXR_continue/H3K27ac_TE_investigation.html) 

[Looking at TE families centered on H3K9me3 ROIs histones](https://reneeisnowhere.github.io/DXR_continue/H3K9me3_TE_investigation.html) 

### Summit and transcription factor motif enrichment data

[H3K27ac TF motif enrichment](https://reneeisnowhere.github.io/DXR_continue/H3K27ac_TF_motifs.html)

[H3K9me3 TF motif enrichment](https://reneeisnowhere.github.io/DXR_continue/H3K9me3_TF_motifs.html)

[H3K27me3 TF motif enrichment](https://reneeisnowhere.github.io/DXR_continue/H3K27me3_TF_motifs.html)

[H3K36me3 TF motif enrichment](https://reneeisnowhere.github.io/DXR_continue/H3K36me3_TF_motifs.html)  


### A little page of cCRE for H3K27ac

[some enrichment and proportion plots for cCREs and H3K27ac summits](https://reneeisnowhere.github.io/DXR_continue/H3K27ac_cisRE.html)

### Examining RNA data with my data

[RNA integration](https://reneeisnowhere.github.io/DXR_continue/H3K27ac_RNA_integration.html)



### Examining ChromHMM states and ROIs
[ChromHMM states and other plots](https://reneeisnowhere.github.io/DXR_continue/chromHMM.html)


### ATAC integration
[First integration of ATAC data with H3K27ac](https://reneeisnowhere.github.io/DXR_continue/ATAC_integration_data1.html)

### Histone signal across TEs

[Plotting of types of TEs, specifically LTRs](https://reneeisnowhere.github.io/DXR_continue/computeMatrixplots.html)
