---
title: "memesuite-TE-enrichment"
author: "Renee Matthews"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: true
  toc_float: true
  toc_depth: 4
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```

```{r package loading}
library(tidyverse)
library(GenomicRanges)
library(plyranges)
library(genomation)
library(readr)
library(rtracklayer)
library(stringr)
library(ggrepel)
library(DT)
library(data.table)
library(readxl)
library(ChIPseeker)
library(smplot2)
library(biomaRt)
library(TFBSTools)
library(JASPAR2022)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(universalmotif)
library(kableExtra)

```









## Exploring TF motifs locations across TE subfamilies
Testing files
```{r data set loading}

##loading TE dataframe
te_df <- read.table("data/Bed_exports/repeatmasker_sets/ERV1/MER61E_ERV1_LTR.bed", header=FALSE) # or your BED
colnames(te_df) <- c("chr","start","end","name","score","strand")
##checking for NAs
sum(is.na(te_df$start))
sum(is.na(te_df$end))
##cleaning TE dataframe (ususally not need, this is just in case)
te_df_clean <- te_df[!is.na(te_df$start) & !is.na(te_df$end), ]
##Convert to Granges
te_gr <- GRanges(
  seqnames = te_df_clean$chr,
  ranges = IRanges(start=te_df_clean$start, end=te_df_clean$end),
  strand = te_df_clean$strand)
### loading fimo for TE
fimo <- read.delim("C:/Users/renee/Other_projects_data/DXR_data/TE_xstreme_results/MER61E_ERV1_LTR_xstreme/fimo_out_1/fimo.tsv")

##checking fimo for NA_s
sum(is.na(fimo$start))
sum(is.na(fimo$stop))
##cleaning fimo

fimo_clean <- fimo[!is.na(fimo$start) & !is.na(fimo$stop), ]

##making grages of fimo
fimo_gr <- GRanges(
  seqnames = fimo_clean$sequence_name,
  ranges = IRanges(start = fimo_clean$start, end = fimo_clean$stop),
  strand = fimo_clean$strand,
  score = fimo_clean$score)


ERV1_summary_char <- read.csv(file.path("data/Other_paper_data/ERV1_file_summary.csv"))

ERV1_summary_char %>% 
  dplyr::filter(filename=="MER61E_ERV1_LTR.bed")

RNA_full_toptable <-  readRDS("data/Other_paper_data/RNA_full_toptable.RDS")


```
 overlapping and computing relative positions

```{r, eval=FALSE}
hits <- findOverlaps(fimo_gr, te_gr)
rel_pos <- (start(fimo_gr)[queryHits(hits)] - start(te_gr)[subjectHits(hits)]) /
           width(te_gr)[subjectHits(hits)]
rel_pos <- pmin(pmax(rel_pos, 0), 1)

df <- data.frame(rel_pos = rel_pos)

ggplot(df, aes(x = rel_pos)) +
  geom_density(fill = "steelblue", alpha = 0.5) +
  labs(x = "Relative position in TE", y = "Motif density") +
  theme_classic() +
  ggtitle("Motif of Fimo1 distribution along TE sequences")


```
## MER61E density Plots {.tabset .tabset-dropdown}


```{r}
# ==============================================
# Function: plot_fimo_motifs
# ==============================================

plot_fimo_motifs <- function(fimo_root_dir, te_bed_file) {
  
  # # Create output dir if it doesn't exist
  # dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
  # 
  # ------------------------------
  # Load TE BED file
  # ------------------------------
  te_df <- read.table(te_bed_file, header = FALSE, stringsAsFactors = FALSE)
  colnames(te_df) <- c("chr","start","end","name","score","strand")
  te_df <- te_df[!is.na(te_df$start) & !is.na(te_df$end) & (te_df$start <= te_df$end), ]
  te_gr <- GRanges(
    seqnames = te_df$chr,
    ranges = IRanges(start = te_df$start, end = te_df$end),
    strand = te_df$strand
  )
  
  # ------------------------------
  # Find all FIMO directories
  # ------------------------------
  fimo_dirs <- list.dirs(fimo_root_dir, recursive = FALSE)
  
  for (fimo_subdir in fimo_dirs) {
    
    fimo_file <- file.path(fimo_subdir, "fimo.tsv")
    
    if (!file.exists(fimo_file)) {
      message("Skipping ", fimo_subdir, ": fimo.tsv not found")
      next
    }
    
    message("Processing ", fimo_file)
    
    # ------------------------------
    # Load and clean FIMO
    # ------------------------------
    fimo <- read.delim(fimo_file, stringsAsFactors = FALSE)
    fimo <- fimo[!is.na(fimo$start) & !is.na(fimo$stop) & (fimo$start <= fimo$stop), ]
    motif_name <- unique(fimo$motif_alt_id)
    
    if (length(motif_name) > 1) {motif_name <- motif_name[1]}

    
    if (nrow(fimo) == 0) {
      message("No valid FIMO entries for ", fimo_subdir)
      next
    }
    
    fimo_gr <- GRanges(
      seqnames = fimo$sequence_name,
      ranges = IRanges(start = fimo$start, end = fimo$stop),
      strand = fimo$strand,
      score = fimo$score
    )
    
    # ------------------------------
    # Find overlaps with TEs
    # ------------------------------
    hits <- findOverlaps(fimo_gr, te_gr)
    
    if (length(hits) == 0) {
      message("No overlaps found for ", fimo_subdir)
      next
    }
    
    # ------------------------------
    # Compute relative positions
    # ------------------------------
    rel_pos <- (start(fimo_gr)[queryHits(hits)] - start(te_gr)[subjectHits(hits)]) /
               width(te_gr)[subjectHits(hits)]
    rel_pos <- pmin(pmax(rel_pos, 0), 1)
    
    df <- data.frame(rel_pos = rel_pos)
    
    # ------------------------------
    # Plot density
    # ------------------------------
   
    cat(paste0("### MER61E ", motif_name, "\n\n"))
    p <- ggplot(df, aes(x = rel_pos)) +
      geom_density(fill = "steelblue", alpha = 0.5) +
      labs(x = "Relative position in TE", y = "Motif density") +
      theme_classic() +
      ggtitle(paste("Motif distribution:", basename(fimo_subdir),"\n",motif_name))
    
   print(p)
   cat("\n\n")
  }
  
 
}

```



```{r}
plot_fimo_motifs("C:/Users/renee/Other_projects_data/DXR_data/TE_xstreme_results/MER61E_ERV1_LTR_xstreme", "data/Bed_exports/repeatmasker_sets/ERV1/MER61E_ERV1_LTR.bed")
```

```{r}
MER61E_sea <- read.delim("C:/Users/renee/Other_projects_data/DXR_data/TE_sea_jaspar_results/MER61E_ERV1_LTR_sea_jaspar/sea.tsv")


motif_ids <- unique(MER61E_sea$ID)
  
opts <- list(
  collection = "CORE",
  tax_group = "vertebrates",
  all_versions = TRUE
)

pfm_list <- getMatrixSet(JASPAR2022, opts)
pfm_subset <- pfm_list[names(pfm_list) %in% motif_ids]
 ### only selecting the first tag...
jaspar_df <- data.frame(
  motif_id = names(pfm_subset),
  TF = sapply(pfm_subset, function(x) x@name),
  family = sapply(pfm_subset, function(x) {
    if (is.null(x@tags$family)) return(NA)
    x@tags$family[1]}))

MER61E_sea %>% 
  left_join(jaspar_df, by = c("ID"="motif_id")) %>% 
  dplyr::filter(!is.na(TF)) %>% 
   arrange(desc(ENR_RATIO)) %>%
   mutate(ALT_ID = fct_reorder(ALT_ID, ENR_RATIO)) %>% 
  slice_head(n = 25) %>% 
  mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
  ggplot(., aes (y= ALT_ID)) +
  geom_col(aes(x=log10Evalue, fill=family))+
  geom_point(aes(x=ENR_RATIO/4), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~.*4,name="Enrichment Ratio"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("Top 25 TF motifs by Enrichment ratio for MER61E TEs"))

```

```{r , fig.width=12}
MER61E_sea %>% 
  left_join(jaspar_df, by = c("ID"="motif_id")) %>% 
  filter(!is.na(TF)) %>% 
  group_by(family) %>% 
  slice_max(ENR_RATIO, n = 1, with_ties = FALSE) %>%   # ✅ best per family
  ungroup() %>% 
  arrange(desc(ENR_RATIO)) %>% 
  slice_head(n = 25) %>% 
  mutate(
    ALT_ID = fct_reorder(ALT_ID, ENR_RATIO),
    log10Evalue = -log10(EVALUE)
  ) %>% 
  ggplot(aes(y = ALT_ID)) +
  geom_col(aes(x =(log10Evalue), fill = family)) +
  geom_point(aes(x = ENR_RATIO/3), size = 4) +
  scale_x_continuous(
    expand = c(0, .125),
    sec.axis = sec_axis(~.*3, name = "Enrichment Ratio")
  ) +
  theme_classic() +
  ylab("Enriched TF motif") +
  ggtitle("Top 25 TF motifs by Enrichment ratio for MER61E TEs grouped by family")

```

```{r, fig.width=12}
MER61C_sea <- read.delim("C:/Users/renee/Other_projects_data/DXR_data/TE_sea_jaspar_results/MER61C_ERV1_LTR_sea_jaspar/sea.tsv")


motif_ids_c <- unique(MER61C_sea$ID)
  
# opts <- list(
#   collection = "CORE",
#   tax_group = "vertebrates",
#   all_versions = TRUE
# )

# pfm_list <- getMatrixSet(JASPAR2022, opts)
pfm_subset_c <- pfm_list[names(pfm_list) %in% motif_ids_c]
 ### only selecting the first tag...
jaspar_df_c <- data.frame(
  motif_id = names(pfm_subset_c),
  TF = sapply(pfm_subset_c, function(x) x@name),
  family = sapply(pfm_subset_c, function(x) {
    if (is.null(x@tags$family)) return(NA)
    x@tags$family[1]}))

MER61C_sea %>% 
  left_join(jaspar_df_c, by = c("ID"="motif_id")) %>% 
  dplyr::filter(!is.na(TF)) %>% 
   arrange(desc(ENR_RATIO)) %>%
   mutate(ALT_ID = fct_reorder(ALT_ID, ENR_RATIO)) %>% 
  slice_head(n = 25) %>% 
  mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
  ggplot(., aes (y= ALT_ID)) +
  geom_col(aes(x=log10Evalue, fill=family))+
  geom_point(aes(x=ENR_RATIO*2), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./2,name="Enrichment Ratio"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("Top 25 TF motifs by Enrichment ratio for MER61C TEs"))

 
  
```

```{r}
HERV1_LTRa_sea <- read.delim("C:/Users/renee/Other_projects_data/DXR_data/TE_sea_jaspar_results/HERV1_LTRa_ERV1_LTR_sea_jaspar/sea.tsv")


motif_ids_HERV1_LTRa <- unique(HERV1_LTRa_sea$ID)
  
# opts <- list(
#   collection = "CORE",
#   tax_group = "vertebrates",
#   all_versions = TRUE
# )

# pfm_list <- getMatrixSet(JASPAR2022, opts)
pfm_subset_HERV1_LTRa <- pfm_list[names(pfm_list) %in% motif_ids_HERV1_LTRa]
 ### only selecting the first tag...
jaspar_df_HERV1_LTRa <- data.frame(
  motif_id = names(pfm_subset_HERV1_LTRa),
  TF = sapply(pfm_subset_HERV1_LTRa, function(x) x@name),
  family = sapply(pfm_subset_HERV1_LTRa, function(x) {
    if (is.null(x@tags$family)) return(NA)
    x@tags$family[1]}))

HERV1_LTRa_sea %>% 
  left_join(jaspar_df_HERV1_LTRa, by = c("ID"="motif_id")) %>% 
  dplyr::filter(!is.na(TF)) %>% 
   arrange(desc(ENR_RATIO)) %>%
   mutate(ALT_ID = fct_reorder(ALT_ID, ENR_RATIO)) %>% 
  slice_head(n = 25) %>% 
  mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
  ggplot(., aes (y= ALT_ID)) +
  geom_col(aes(x=log10Evalue, fill=family))+
  geom_point(aes(x=ENR_RATIO*.1), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./.1,name="Enrichment Ratio"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("Top 25 TF motifs by Enrichment ratio for HERV1_LTRa TEs"))

 
  
```

```{r}
### Expression related?

MER61E_sea %>% 
  left_join(jaspar_df, by = c("ID"="motif_id")) %>% 
  dplyr::filter(!is.na(TF)) %>% 
  dplyr::filter(ALT_ID %in% RNA_full_toptable$SYMBOL) %>% 
   arrange(desc(ENR_RATIO)) %>%
   mutate(ALT_ID = fct_reorder(ALT_ID, ENR_RATIO)) %>% 
  slice_head(n = 25) %>% 
  mutate(log10Evalue= log(EVALUE, base = 10)*(-1)) %>% 
  ggplot(., aes (y= ALT_ID)) +
  geom_col(aes(x=log10Evalue, fill=family))+
  geom_point(aes(x=ENR_RATIO/4), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~.*4,name="Enrichment Ratio"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste("Top 25 expressed TF motifs by Enrichment ratio for MER61E TEs"))
```
```{r}
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
genes_gr <- genes(txdb)
sites <- read.delim("C:/Users/renee/Other_projects_data/DXR_data/TE_sea_jaspar_results/MER61E_ERV1_LTR_sea_jaspar/sites.tsv", header=TRUE)

tp53_sites <- sites %>% 
  dplyr::filter(motif_ALT_ID=="TP53")

tp53_gr <-  GRanges(seqnames = tp53_sites$seq_ID,
  ranges = IRanges(start = tp53_sites$site_Start, end = tp53_sites$site_End),
  motif = tp53_sites$motif_ALT_ID,
  name="MER61E")


hits <- distanceToNearest(tp53_gr, genes_gr)

# extract results
res <- data.frame(
  MER61E_site = mcols(tp53_gr)$name[queryHits(hits)],
  gene = names(genes_gr)[subjectHits(hits)],
  distance = mcols(hits)$distance
)

RNA_full_toptable <-  readRDS("data/Other_paper_data/RNA_full_toptable.RDS")

Symbol_lookup <- RNA_full_toptable %>% 
  dplyr::select (Entrez_ID,SYMBOL) %>% 
  distinct(Entrez_ID,SYMBOL)

res %>%
  mutate(gene=as.numeric(gene)) %>% 
  dplyr::left_join(Symbol_lookup, by=c("gene"="Entrez_ID"))

```

```{r pwm based on TingWang, eval=FALSE}


A <- c(0.48,-0.06,0.72,-3.59, 0.99,-0.07,-2.17,-2.17,-2.41,-0.65) 
C <- c(-1.21, -1.89,-2.29,1.34,-1.68,-1.74,-2.95, 0.55, 1.03, 0.44)
G <- c(0.44,1.03,0.55,-2.95,-1.74, -1.68,1.34,-2.29,-1.89, -1.21)
T <- c(-0.65,-2.41,-2.17,-2.17,-0.07, 0.99,-3.59,0.72,-0.06,0.48)

TP53_half_mat <- rbind(A,C,G,T)

# background frequencies
bg <- c(A=0.25, C=0.25, G=0.25, T=0.25)

# convert log-odds → probabilities
TP53_half_prob_mat <- apply(TP53_half_mat, 2, function(col) {
  p <- bg * (2^col)
  p / sum(p)  # normalize
})

# TP53_half_prob_mat <- t(TP53_half_prob_mat)

rownames(TP53_half_prob_mat) <- c("A","C","G","T")

colSums(TP53_half_prob_mat) #all ones?  sanity checking as they should be
TP53_half_prob_mat <- as.matrix(TP53_half_prob_mat)

TP53_half_motif <- create_motif(TP53_half_prob_mat, name = "TP53_half_motif_paper_pwm", alphabet = "DNA")


write_meme(TP53_half_motif, file = "data/Other_paper_data/TP53_half_motif_paper_pwm.meme")

```

### looking a TP53 half sites from Ting Wang paper


```{r}

plot_p53_motifs <- function(fimo_root_dir, te_bed_file) {
  
  # # Create output dir if it doesn't exist
  # dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
  # 
  # ------------------------------
  # Load TE BED file
  # ------------------------------
  te_df <- read.table(te_bed_file, header = FALSE, stringsAsFactors = FALSE)
  colnames(te_df) <- c("chr","start","end","name","score","strand")
  te_df <- te_df[!is.na(te_df$start) & !is.na(te_df$end) & (te_df$start <= te_df$end), ]
  te_gr <- GRanges(
    seqnames = te_df$chr,
    ranges = IRanges(start = te_df$start, end = te_df$end),
    strand = te_df$strand
  )
  
  # ------------------------------
  # Find all FIMO directories
  # ------------------------------
  # fimo_dirs <- list.dirs(fimo_root_dir, recursive = FALSE)
  # 
  # for (fimo_subdir in fimo_dirs) {
    
    fimo_file <- file.path(fimo_root_dir, "fimo.tsv")
    # 
    # if (!file.exists(fimo_file)) {
    #   message("Skipping ", fimo_subdir, ": fimo.tsv not found")
    #   next
    # }
    
    message("Processing ", fimo_file)
    
    # ------------------------------
    # Load and clean FIMO
    # ------------------------------
    fimo <- read.delim(fimo_file, stringsAsFactors = FALSE)
  
    fimo <- fimo[!is.na(fimo$start) & !is.na(fimo$stop) & (fimo$start <= fimo$stop), ]
    motif_name <- unique(fimo$motif_alt_id)
    
    if (length(motif_name) > 1) {motif_name <- motif_name[1]}

    
    if (nrow(fimo) == 0) {
      message("No valid FIMO entries for ", fimo_subdir)
      next
    }
    
    fimo_gr <- GRanges(
      seqnames = fimo$sequence_name,
      ranges = IRanges(start = fimo$start, end = fimo$stop),
      strand = fimo$strand,
      score = fimo$score
    )
    
    # ------------------------------
    # Find overlaps with TEs
    # ------------------------------
    hits <- findOverlaps(fimo_gr, te_gr)
    
    if (length(hits) == 0) {
      message("No overlaps found for ", fimo_root_dir)
      next
    }
    
    # ------------------------------
    # Compute relative positions
    # ------------------------------
    rel_pos <- (start(fimo_gr)[queryHits(hits)] - start(te_gr)[subjectHits(hits)]) /
               width(te_gr)[subjectHits(hits)]
    rel_pos <- pmin(pmax(rel_pos, 0), 1)
    
    df <- data.frame(rel_pos = rel_pos)
    
    # ------------------------------
    # Plot density
    # ------------------------------
   
    cat(paste0("### MER61E ", motif_name, "\n\n"))
    p <- ggplot(df, aes(x = rel_pos)) +
      geom_density(fill = "steelblue", alpha = 0.5) +
      labs(x = "Relative position in TE", y = "Motif density") +
      theme_classic() +
      ggtitle(paste("TP53 halfsite motif distribution:", basename(fimo_root_dir),"\n",motif_name))
    
   print(p)
   cat("\n\n")
  }
  
```

```{r}
plot_p53_motifs("C:/Users/renee/Other_projects_data/DXR_data/fimo_results/MER61E_ERV1_LTR_fimo", "data/Bed_exports/repeatmasker_sets/ERV1/MER61E_ERV1_LTR.bed")

plot_p53_motifs("C:/Users/renee/Other_projects_data/DXR_data/fimo_results/MER61C_ERV1_LTR_fimo", "data/Bed_exports/repeatmasker_sets/ERV1/MER61C_ERV1_LTR.bed")

plot_p53_motifs("C:/Users/renee/Other_projects_data/DXR_data/fimo_results/MER61A_ERV1_LTR_fimo", "data/Bed_exports/repeatmasker_sets/ERV1/MER61A_ERV1_LTR.bed")




```

```{r plot p53 locations}

plot_p53_motifs_all <- function(fimo_root_dir, te_bed_base_dir) {
 
  
  # Initialize results list
  results_list <- list()
  
  # Find all directories ending with "_fimo"
  fimo_dirs <- list.dirs(fimo_root_dir, recursive = FALSE)
  fimo_dirs <- fimo_dirs[grepl("_fimo$", basename(fimo_dirs))]
  
  for (fimo_dir in fimo_dirs) {
    base_name <- sub("_fimo$", "", basename(fimo_dir))
    
    # Find FIMO file
    fimo_file <- file.path(fimo_dir, "fimo.tsv")
    if (!file.exists(fimo_file)) {
      message("Skipping ", fimo_dir, ": fimo.tsv not found")
      next
    }
    
    # Find corresponding TE BED file
    te_file <- file.path(te_bed_base_dir, paste0(base_name, ".bed"))
    if (!file.exists(te_file)) {
      message("Skipping ", base_name, ": TE BED file not found")
      next
    }
    
    # ------------------------------
    # Load TE BED file
    # ------------------------------
    te_df <- read.table(te_file, header = FALSE, stringsAsFactors = FALSE)
    colnames(te_df) <- c("chr","start","end","name","score","strand")
    te_df <- te_df[!is.na(te_df$start) & !is.na(te_df$end) & (te_df$start <= te_df$end), ]
    te_gr <- GRanges(
      seqnames = te_df$chr,
      ranges = IRanges(start = te_df$start, end = te_df$end),
      strand = te_df$strand
    )
    
    # ------------------------------
    # Load FIMO
    # ------------------------------
    fimo <- read.delim(fimo_file, stringsAsFactors = FALSE)
    
    # Filter TP53 motifs
    if ("motif_id" %in% colnames(fimo)) {
      fimo <- fimo[grepl("TP53", fimo$motif_id, ignore.case = TRUE), ]
    } else {
      message("No motif_id column in ", fimo_file)
      next
    }
    
    # Skip if no motifs found
    if (nrow(fimo) == 0) {
      message("No TP53 motifs in ", base_name)
      results_list[[paste0(base_name, "_no_hits")]] <- data.frame(
        TE_name = base_name,
        motif_name = NA,
        total_TEs = length(te_gr),
        TEs_with_TP53 = 0,
        total_TP53_hits = 0,
        occupancy = 0
      )
      next
    }
    
    # Clean FIMO entries
    fimo <- fimo[!is.na(fimo$start) & !is.na(fimo$stop) & (fimo$start <= fimo$stop), ]
    
    motif_name <- unique(fimo$motif_id)
    
    # Loop over each motif separately (in case multiple motifs exist)
    for (mn in motif_name) {
      fimo_motif <- fimo[fimo$motif_id == mn, ]
      
      fimo_gr <- GRanges(
        seqnames = fimo_motif$sequence_name,
        ranges = IRanges(start = fimo_motif$start, end = fimo_motif$stop),
        strand = fimo_motif$strand,
        score = fimo_motif$score
      )
      
      # ------------------------------
      # Overlaps
      # ------------------------------
      hits <- findOverlaps(fimo_gr, te_gr)
      n_te_total <- length(te_gr)
      
      if (length(hits) == 0) {
        message("No overlaps for motif ", mn, " in ", base_name)
        results_list[[paste0(base_name, "_", mn)]] <- data.frame(
          TE_name = base_name,
          motif_name = mn,
          total_TEs = n_te_total,
          TEs_with_TP53 = 0,
          total_TP53_hits = 0,
          occupancy = 0
        )
        next
      }
      
      n_te_with_hits <- length(unique(subjectHits(hits)))
      n_total_hits <- length(hits)
      occupancy <- n_te_with_hits / n_te_total
      
      # ------------------------------
      # Compute relative positions
      # ------------------------------
      rel_pos <- (start(fimo_gr)[queryHits(hits)] - start(te_gr)[subjectHits(hits)]) /
                 width(te_gr)[subjectHits(hits)]
      rel_pos <- pmin(pmax(rel_pos, 0), 1)
      df <- data.frame(rel_pos = rel_pos)
      
      # ------------------------------
      # Store results
      # ------------------------------
      results_list[[paste0(base_name, "_", mn)]] <- data.frame(
       
        motif_name = mn,
        TE_name = base_name,
        total_TEs = n_te_total,
        TEs_with_TP53 = n_te_with_hits,
        total_TP53_hits = n_total_hits,
        occupancy = occupancy
      )
      
      # ------------------------------
      # Plot density
      # ------------------------------
      cat(paste0("### ", base_name, " ", mn, "\n"))
      cat(base_name, "| total TEs:", n_te_total, "| with TP53:", n_te_with_hits, 
          "| hits:", n_total_hits, "\n")
      cat("Sequences with TP53 motif: ", round(occupancy * 100, 2), "%\n\n")
      
      p <- ggplot(df, aes(x = rel_pos)) +
        geom_density(fill = "steelblue", alpha = 0.5) +
        labs(x = "Relative position in TE", y = "Motif density") +
        theme_classic() +
        ggtitle(paste0("TP53 motif distribution: ", base_name,
                       "\nSequences with motif: ", round(occupancy * 100, 1), "%"))
      print(p)
      cat("\n\n")
    }
  } # end fimo_dirs loop
  
  # Combine all results into one data frame
  results_df <- do.call(rbind, results_list)
  
  print(results_df)
  return(results_df)
}
```

```{r for_tp53motifs}
Astorage <- plot_p53_motifs_all("C:/Users/renee/Other_projects_data/DXR_data/fimo_results", "data/Bed_exports/repeatmasker_sets/ERV1")

kable(Astorage, caption = "TP53 motif occupancy per TE family") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE) %>%
  column_spec(1, bold = TRUE) %>%          # make TE_name bold
  column_spec(6, color = "white", background = spec_color(Astorage$occupancy, end = 0.9))  # color occupancy
```


